import { useState } from 'react';
import { ArrowUpRight, Maximize2, Users, BedDouble, Image as ImageIcon } from 'lucide-react';
import { FASTBOOKING_URL } from './booking.js';

// Room details and these exact image URLs were read from the hotel's Fastbooking page.
const IMAGE_BASE = 'https://d3ehecxdotm942.cloudfront.net/b01bf1a53760e71e7923a93af7d0f295/2544e5b1e7659a7/';
const rooms = [
  { id:'standard', name:'Standard Room no Elevator', size:'28–30', occupancy:2, bed:'doubleTwin', features:['wifi','air','balcony','shower'], images:['553df2905579e8045978fa69914aa41d','3b5dc5c8965ce0d8206eedc19f535b30','d628e2050cf1c19394982b9e39535b63','a296c8230a268603a3b40d7a223c937f','32958cbc82558445b7b678d9f044169e'], description:{th:'ห้องพักพร้อมระเบียง พื้นที่ 28–30 ตารางเมตร มีเตียงใหญ่หรือเตียงแฝดตามความพร้อมของห้องพัก',en:'A 28–30 m² room with a balcony and double or twin bedding options, subject to availability.',zh:'28–30平方米客房，设有阳台，可选大床或双床，视供应情况而定。'} },
  { id:'deluxe',name:'Deluxe Room',size:'26',occupancy:3,bed:'doubleTwin',features:['wifi','air','fridge','shower'],images:['e2be65f7bfacf1b2f000015b20eddf10','ed0770a82f63b721548df7901782d5ee','2af6e52e78d49a09cf8b7d7683e84e99','81a717d6f899b552664e18294fbba53c','9cab8b734e755727a05c9bc7329cf45f'],description:{th:'ห้องพักขนาด 26 ตารางเมตร พร้อมทีวี ตู้เย็น และห้องน้ำฝักบัว มีตัวเลือกเตียงใหญ่หรือเตียงแฝด',en:'A 26 m² room with a television, refrigerator and shower, with double or twin bedding options.',zh:'26平方米客房，配备电视、冰箱和淋浴间，提供大床或双床选择。'} },
  {id:'executive',name:'Executive Room',size:'30',occupancy:3,bed:'doubleTwin',features:['wifi','air','balcony','shower'],images:['2d278fdb465917058de9a39db7466b0c','cbdcef2e0345f9af16e2ccc46996d61b','a02d2100f903cc24fc6297c23b7df63b','be9341cc77ababa1c4f9feec36667b83','b24e4013d79176c7485a0cf65961dd51'],description:{th:'ห้องพักขนาด 30 ตารางเมตร พร้อมระเบียงส่วนตัว ตู้เสื้อผ้าขนาดใหญ่ และพื้นที่เก็บสัมภาระ',en:'A 30 m² room with a private balcony, a large wardrobe and space for luggage.',zh:'30平方米客房，设有私人阳台、大衣柜及行李存放空间。'} },
  {id:'executive-pool-view',name:'Executive Pool View',size:'30',occupancy:3,bed:'kingTwin',features:['wifi','air','poolView','balcony'],images:['1bd9281d22a4ce937142ebd4bb57c454','0b0ae0e1fc4ebc722de333cf8692beff','3789b9b75d24477d6af1f456e3afe2b6','d8a724f2693e9ec216b1a165c8072216','cb78d03be4e4471b0dabdaf44fb02d81'],description:{th:'ห้องพักขนาด 30 ตารางเมตร พร้อมระเบียงส่วนตัวมองเห็นสระว่ายน้ำ มีตัวเลือกเตียงคิงไซส์หรือเตียงแฝด',en:'A 30 m² room with a private balcony overlooking the pool, with king or twin bedding options.',zh:'30平方米客房，私人阳台可欣赏泳池景观，提供特大床或双床选择。'} },
  {id:'premier-junior-suite',name:'Premier Junior Suite',size:'38',occupancy:3,bed:'king',features:['wifi','air','bathtub','bathrobe'],images:['84543c10968f2f67bd171d5f3ad15647','ea4f5f5c410074ec8b0605d73ddc6208','04a09e57d97fd2038ab9bc0f4463c139','aeaf2a5292d23df94628ff2c898358bf','2fbc29675d980192f3cc7674ca33e282'],description:{th:'ห้องสวีทขนาด 38 ตารางเมตร พร้อมเตียงคิงไซส์และห้องน้ำกระจกที่มีอ่างอาบน้ำสำหรับช่วงเวลาพักผ่อน',en:'A 38 m² suite with king bedding and a glass bathroom with a bathtub.',zh:'38平方米套房，配备特大床及带浴缸的玻璃浴室。'} },
  {id:'premier-pool-access',name:'Premier Pool Access',size:'30',occupancy:3,bed:'doubleKing',features:['wifi','air','balcony','bathtub'],images:['364b6e59aba3d5ecec2adc71658531ad','cac569d6cd58119fc0072e8e89d4a2f2','7e059e78e72d11475510c5e37675acd9','d9066fa24249bc54abfa3d796021a20e','844e0413999350417e99b2a610a2f53e'],description:{th:'ห้อง Premier Pool Access ขนาด 30 ตารางเมตร พร้อมระเบียงส่วนตัว อ่างอาบน้ำ และเสื้อคลุมอาบน้ำ',en:'A 30 m² Premier Pool Access room with a private balcony, bathtub and bathrobes.',zh:'30平方米泳池直通客房，设有私人阳台、浴缸及浴袍。'} }
];
const copy = {
  th:{heading:'เลือกห้องพักที่เหมาะกับคุณ',intro:'สำรวจภาพห้องจริง ขนาดห้อง และสิ่งอำนวยความสะดวก ก่อนตรวจสอบห้องว่างสำหรับวันเดินทางของคุณ',category:'ประเภทห้องพัก',book:'ตรวจสอบราคาและจอง',bookingNote:'เลือกวันเข้าพัก ประเภทห้อง และแพ็กเกจบน Fastbooking ของโรงแรม ราคาและห้องว่างขึ้นอยู่กับวันที่เลือก',details:'สิ่งอำนวยความสะดวก',adults:'ผู้ใหญ่',guests:'ท่าน',upTo:'สูงสุด',area:'ตร.ม.',doubleTwin:'เตียงใหญ่ / เตียงแฝด',kingTwin:'คิงไซส์ / เตียงแฝด',king:'เตียงคิงไซส์',doubleKing:'เตียงใหญ่ / คิงไซส์',noElevator:'อาคาร 4 ชั้น ไม่มีลิฟต์',note:'ชนิดเตียงและการรองรับผู้เข้าพักเพิ่มเติมเป็นไปตามห้องว่างและเงื่อนไขของโรงแรม',image:'ขยายภาพ',thumbnail:'ดูภาพ',unavailable:'ไม่สามารถโหลดภาพได้',source:'รายละเอียดจาก Fastbooking',wifi:'Wi-Fi ฟรี',air:'เครื่องปรับอากาศ',balcony:'ระเบียง',shower:'ฝักบัว',fridge:'ตู้เย็น',poolView:'วิวสระว่ายน้ำ',bathtub:'อ่างอาบน้ำ',bathrobe:'เสื้อคลุมอาบน้ำ'},
  en:{heading:'Find your kind of stay',intro:'Explore real room photographs, room sizes and amenities, then check availability for your travel dates.',category:'Room types',book:'Check rates & book',bookingNote:'Choose your dates, room type and package on the hotel’s Fastbooking page. Rates and availability depend on your selected dates.',details:'Room amenities',adults:'adults',guests:'guests',upTo:'Up to',area:'m²',doubleTwin:'Double / Twin',kingTwin:'King / Twin',king:'King bed',doubleKing:'Double / King',noElevator:'4-storey building · No elevator',note:'Bedding and arrangements for additional guests are subject to availability and hotel conditions.',image:'Enlarge image',thumbnail:'View image',unavailable:'Image unavailable',source:'Room details from Fastbooking',wifi:'Free Wi-Fi',air:'Air conditioning',balcony:'Balcony',shower:'Shower',fridge:'Refrigerator',poolView:'Pool view',bathtub:'Bathtub',bathrobe:'Bathrobes'},
  zh:{heading:'找到适合您的客房',intro:'查看真实客房照片、面积和设施，再查询出行日期的空房。',category:'房型',book:'查询房价并预订',bookingNote:'在酒店 Fastbooking 页面选择日期、房型及套餐。房价及空房以所选日期为准。',details:'客房设施',adults:'位成人',guests:'位客人',upTo:'最多',area:'平方米',doubleTwin:'大床 / 双床',kingTwin:'特大床 / 双床',king:'特大床',doubleKing:'大床 / 特大床',noElevator:'4层建筑 · 无电梯',note:'床型及额外住客安排视供应情况及酒店条款而定。',image:'放大图片',thumbnail:'查看图片',unavailable:'图片暂时无法加载',source:'客房资料来自 Fastbooking',wifi:'免费 Wi-Fi',air:'空调',balcony:'阳台',shower:'淋浴',fridge:'冰箱',poolView:'泳池景观',bathtub:'浴缸',bathrobe:'浴袍'}
};
function RoomCard({room,index,c,lang,onImage}) {
  const [selected,setSelected]=useState(0);
  const [failed,setFailed]=useState(false);
  const src=IMAGE_BASE+room.images[selected]+'-w704-scale.jpg';
  return <article id={'room-'+room.id} className="room-card">
    <div className="room-gallery"><button className="room-photo" onClick={()=>onImage({src,alt:room.name})} aria-label={c.image+': '+room.name} disabled={failed}>{failed?<span className="room-image-fallback">{c.unavailable}</span>:<img src={src} alt={room.name} loading="lazy" onError={()=>setFailed(true)}/>}<span className="room-photo-count">{selected+1} / {room.images.length}</span><ImageIcon size={20} aria-hidden="true"/></button>
      <div className="room-thumbnails" role="group" aria-label={room.name}>{room.images.map((id,i)=><button key={id} aria-label={c.thumbnail+' '+(i+1)+': '+room.name} aria-pressed={selected===i} onClick={()=>{setSelected(i);setFailed(false);}}><img src={IMAGE_BASE+id+'-w704-scale.jpg'} alt="" loading="lazy"/></button>)}</div>
    </div>
    <div className="room-copy"><p className="eyebrow">THE VILLE ROOMS · 0{index+1}</p><h2>{room.name}</h2><div className="room-specs"><span><Maximize2 size={17}/>{room.size} {c.area}</span><span><Users size={17}/>{c.upTo} {room.occupancy} {room.id==='standard'?c.adults:c.guests}</span><span><BedDouble size={17}/>{c[room.bed]}</span></div><p className="room-description">{room.description[lang]}</p>{room.id==='standard'&&<p className="room-access-note">{c.noElevator}</p>}<ul className="room-amenities" aria-label={c.details}>{room.features.map(key=><li key={key}>{c[key]}</li>)}</ul><a className="button gold room-book" href={FASTBOOKING_URL} target="_blank" rel="noreferrer" aria-label={c.book+': '+room.name}>{c.book}<ArrowUpRight size={18}/></a><p className="room-availability-note">{c.bookingNote}</p></div>
  </article>;
}
export default function RoomCatalogue({lang,onImage}) {
  const c=copy[lang];
  return <section className="section wrap room-catalogue"><div className="room-introduction"><p className="eyebrow">ROOMS & SUITES</p><h2>{c.heading}</h2><p>{c.intro}</p></div><nav className="room-jump-links" aria-label={c.category}>{rooms.map(room=><a href="#stay" key={room.id} onClick={e=>{e.preventDefault();document.getElementById('room-'+room.id)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}}>{room.name}</a>)}</nav><div className="room-list">{rooms.map((room,index)=><RoomCard key={room.id} room={room} index={index} c={c} lang={lang} onImage={onImage}/>)}</div><p className="room-catalogue-note">{c.note} <a href={FASTBOOKING_URL} target="_blank" rel="noreferrer">{c.source}<ArrowUpRight size={14}/></a></p></section>;
}
